# ------------------------------- 
# SERVER PORT (Render will inject PORT)
# -------------------------------
server.port=${PORT}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true


# -------------------------------
# POSTGRES DB (Render)
# -------------------------------
spring.datasource.url=jdbc:postgresql://dpg-d4dmhpruibrs73dogmfg-a:5432/studentform
spring.datasource.username=studentform_user
spring.datasource.password=RCF7l4QGSWTEjuUJw6dabc7aEf3VyecT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect





# -------------------------------
# LOGGING
# -------------------------------
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
